# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Future Imperfect Plus"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = ["", ""]
features = ["html5", "css3", "responsive"]
min_version = 0.15

[author]
  name = "Jason B.S. Kang"
  homepage = ""

# If porting an existing theme
[original]
  name = "Future Imperfect"
  homepage = "http://html5up.net/future-imperfect"
  repo = ""
